//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoutureEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int ID { get; set; }
        public string BrideFirstName { get; set; }
        public string BrideLastName { get; set; }
        public string GroomFirstName { get; set; }
        public string GroomLastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public Nullable<int> NumberOfGuests { get; set; }
        public Nullable<int> NumberOfBridesmaids { get; set; }
        public Nullable<int> NumberOfGroomsmen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
